"""
Bundled customer support ticket dataset.
40 realistic examples per category × 5 categories = 200 samples.
No internet required — used as default training data.

Categories:
  - Technical Issue
  - Billing
  - Account
  - Shipping
  - Cancellation
"""

TICKETS = {
    "Technical Issue": [
        "My internet connection keeps dropping every few minutes and I cannot work from home.",
        "The application crashes every time I try to open a large file.",
        "My device stopped turning on after I installed the latest software update.",
        "The screen keeps flickering and sometimes goes completely black.",
        "I am getting an error code 500 every time I try to submit the form.",
        "The printer is not being recognized by my laptop even after reinstalling the driver.",
        "My WiFi connection is extremely slow and pages take forever to load.",
        "The app freezes whenever I try to upload a document larger than 5MB.",
        "My computer is running very slowly after the recent system update.",
        "I cannot hear any sound from my speakers even though the volume is turned up.",
        "The camera on my device is not working and shows a black screen.",
        "My keyboard is typing the wrong characters randomly.",
        "The software keeps logging me out automatically every few minutes.",
        "I am unable to install the latest update. It fails at 80% every time.",
        "My device is overheating and shutting down during normal usage.",
        "The touchscreen is not responding to my finger taps correctly.",
        "I cannot send emails. They stay stuck in the outbox and never send.",
        "The battery drains to zero within two hours even when not in use.",
        "My microphone is not being detected during video calls.",
        "The application is not syncing my data across my devices.",
        "I receive a connection timeout error when trying to access the dashboard.",
        "The GPS on my device is showing the wrong location.",
        "My device keeps restarting by itself every hour or so.",
        "The software is not compatible with my operating system version.",
        "I cannot download files. The download starts and then fails immediately.",
        "My external hard drive is not showing up when I plug it in.",
        "The login page is not loading on any browser I try.",
        "I am getting a firewall error when trying to connect to the server.",
        "The notification feature stopped working after the last update.",
        "My device has been stuck on the loading screen for the past two hours.",
        "The video streaming keeps buffering every few seconds.",
        "I cannot pair my Bluetooth device with my computer.",
        "The software update broke my existing settings and preferences.",
        "My device is showing a storage full error even though I deleted many files.",
        "The application is not launching and shows a white blank screen.",
        "I keep getting a certificate error when visiting the website.",
        "My two-factor authentication app is not generating the correct codes.",
        "The file upload feature is not working on the web portal.",
        "I cannot access the settings menu. It keeps crashing immediately.",
        "My account dashboard is loading but showing outdated information.",
    ],

    "Billing": [
        "I was charged twice for the same order this month. Please refund the duplicate.",
        "My credit card was billed but I never received a confirmation or receipt.",
        "I see an unexpected charge on my statement that I did not authorize.",
        "I requested a refund two weeks ago but the money has not returned to my account.",
        "I was overcharged for my subscription. The price is higher than advertised.",
        "My invoice shows the wrong amount. I should have been charged the discounted rate.",
        "I cancelled my subscription last month but I am still being charged.",
        "I need a copy of my invoice for tax purposes. Can you email it to me?",
        "My payment failed but the money was still deducted from my bank account.",
        "I applied a promo code but the discount was not reflected in my final bill.",
        "I need to update my billing address for future invoices.",
        "I was charged for a service I never signed up for.",
        "My annual plan was renewed without any notice or email reminder.",
        "I would like to switch from monthly billing to annual billing.",
        "The VAT on my invoice is incorrect. It is showing the wrong percentage.",
        "I made a payment yesterday but it is still showing as unpaid in the system.",
        "I cannot find my payment history in the account portal.",
        "My bank reversed the charge but the account still shows as unpaid.",
        "I was promised a full refund but only received a partial refund.",
        "I need to change the credit card on file for future payments.",
        "I received a late payment fee but I paid on time. Please remove the fee.",
        "My account was suspended due to a billing error that was not my fault.",
        "I would like an itemized breakdown of all charges from last month.",
        "The free trial ended and I was charged without a warning email.",
        "I see a foreign transaction fee on my bill that I do not understand.",
        "My payment plan was supposed to be zero interest but I was charged interest.",
        "I need to dispute a charge from three months ago.",
        "My corporate account should be tax exempt but I was charged tax.",
        "I made a mistake and paid the wrong amount. How do I fix this?",
        "The upgrade I purchased is not reflected in my current billing cycle.",
        "I need a receipt for my last payment sent to my company email.",
        "My billing cycle date changed without my approval.",
        "I want to set up automatic payments but the option is not available.",
        "I was charged after I downgraded my plan. That should not happen.",
        "My refund was supposed to take 5 business days but it has been 3 weeks.",
        "The coupon I used should have given me 30% off but I was only given 10%.",
        "I need to add a second payment method to my account.",
        "My account balance is showing a negative amount.",
        "I purchased the wrong plan by mistake. Can I get a refund and switch?",
        "I need an official receipt that includes my company name and tax ID.",
    ],

    "Account": [
        "I cannot log into my account. The password I use is not being accepted.",
        "I forgot my password and the reset email is not arriving in my inbox.",
        "My account was locked after too many failed login attempts.",
        "I need to change my email address on the account but the option is greyed out.",
        "I cannot access my account from a new device. It says suspicious activity.",
        "My two-factor authentication is not working and I am locked out.",
        "I want to delete my account and all personal data permanently.",
        "My account profile information is showing the wrong name and address.",
        "I was logged out of my account and now I cannot log back in.",
        "I think someone else has accessed my account without my permission.",
        "I need to merge two accounts that I accidentally created with different emails.",
        "The verification email for my new account never arrived.",
        "I cannot change my phone number on the account settings page.",
        "My account preferences keep resetting to default every time I log in.",
        "I need to update my profile picture but the upload is not working.",
        "My account shows an old address that I want to update.",
        "I accidentally deactivated my account. How do I reactivate it?",
        "I want to enable or disable email notifications in my account settings.",
        "My saved preferences and settings have disappeared from my account.",
        "I cannot link my social media account to my profile.",
        "I need to add another user to my account with limited permissions.",
        "My username is showing incorrectly across the platform.",
        "I want to change my display name but there is no option to do so.",
        "The security question I set up is not being accepted when I try to recover my account.",
        "I need to close my account because I am moving to a different service.",
        "My account history and past orders are no longer showing.",
        "I want to download all the data associated with my account.",
        "I need to transfer my account ownership to someone else.",
        "My account is showing as inactive even though I use it every week.",
        "I cannot set up a new password. The system says my password does not meet requirements.",
        "I received an email saying my account was accessed from a different country.",
        "My account was created but I never received the welcome email.",
        "I need to update my date of birth in the account settings.",
        "The privacy settings on my account keep reverting after I save them.",
        "I want to opt out of marketing emails but cannot find the option.",
        "My account was suspended and I do not know why.",
        "I need to verify my identity to unlock a feature in my account.",
        "I cannot see my saved items and lists in my account.",
        "My account is connected to the wrong phone number.",
        "I need to reset my security PIN for my account.",
    ],

    "Shipping": [
        "My order was supposed to arrive three days ago but it has not been delivered.",
        "The tracking number I received is not showing any updates for the past week.",
        "My package was marked as delivered but I never received it.",
        "I received the wrong item in my shipment. I ordered something different.",
        "My package arrived damaged. The box was crushed and the item is broken.",
        "I need to change the delivery address after placing the order.",
        "My order was split into two shipments but I only received one.",
        "The estimated delivery time has passed and there is no update on my order.",
        "I was not home when the delivery was attempted. How do I reschedule?",
        "My package has been stuck at the customs office for over two weeks.",
        "I want to upgrade my shipping to express delivery for an existing order.",
        "I never received the shipping confirmation email after placing my order.",
        "My order shows as shipped but the tracking has not moved in five days.",
        "I received only half of my order. The other items are missing.",
        "The courier left my package outside in the rain and it is damaged.",
        "I ordered two of the same item but only one was included in the box.",
        "My shipment was returned to the sender. I do not know why.",
        "I need the contact number for the courier handling my delivery.",
        "The delivery driver left a note but I cannot schedule a pickup at the depot.",
        "My international shipment has not arrived within the promised timeframe.",
        "I received a notification that my package is being returned but I was home all day.",
        "The packing slip inside my order shows the wrong items.",
        "My order was lost during transit according to the carrier.",
        "I need to file a claim for a damaged item I received.",
        "The delivery estimate on the website was 3 days but it has been 10 days.",
        "I accidentally provided the wrong zip code. Can you update the address?",
        "My package requires a signature but no one is home during the day.",
        "I received someone else's order by mistake.",
        "I need to know the exact dimensions and weight of my shipment.",
        "My order is showing as out for delivery but it is already midnight.",
        "I want to request express shipping but the option is not available at checkout.",
        "The fragile items in my order were not packed with enough protective material.",
        "I am being asked to pay additional customs fees that were not mentioned.",
        "My order was cancelled automatically after showing as processing for too long.",
        "I need proof of delivery documentation for my records.",
        "The tracking page shows delivered to a different address than mine.",
        "My subscription box did not arrive this month.",
        "I need to delay my shipment because I will be traveling.",
        "The courier said they attempted delivery but my building has a front desk.",
        "I want to return a delivered item but the return label was not included.",
    ],

    "Cancellation": [
        "I want to cancel my subscription immediately and stop future charges.",
        "I would like to cancel my order that I placed an hour ago.",
        "I need to cancel my account before the next billing date.",
        "I want to downgrade my plan instead of cancelling completely.",
        "I accidentally signed up for the premium plan and want to cancel it.",
        "I need to cancel a scheduled service appointment for next week.",
        "I want to return a product I bought last week and get a full refund.",
        "I would like to cancel the automatic renewal of my annual subscription.",
        "I am moving abroad and need to cancel all my services.",
        "I want to cancel my free trial before it converts to a paid subscription.",
        "I need to cancel my reservation and get my deposit back.",
        "I signed up by mistake and want to cancel before being charged.",
        "I want to pause my subscription for three months instead of cancelling.",
        "I cannot find the cancel button in my account settings.",
        "I need to cancel a recurring payment arrangement.",
        "I was told I could cancel within 30 days for a full refund. I am on day 25.",
        "I want to cancel the additional services I added last month.",
        "I need to cancel my corporate account and all associated user accounts.",
        "I want to opt out of the annual plan and switch to monthly before it renews.",
        "My cancellation request from last week was not processed.",
        "I submitted a cancellation form but I am still receiving charges.",
        "I want to cancel my order that shows as processing.",
        "I need to cancel a bulk order I placed this morning.",
        "I would like to end my service agreement before the contract expires.",
        "I want to cancel the upgrade I requested yesterday.",
        "I need to cancel my pre-order for an item that has not shipped yet.",
        "I want to cancel the warranty extension I purchased.",
        "I need to remove additional features I added to my base subscription.",
        "I want to discontinue the paper billing option.",
        "I need to cancel a group reservation for 10 people.",
        "I would like to request a cancellation and full refund within my cooling off period.",
        "I want to cancel my gym membership effective end of this month.",
        "I need to terminate my service before the end of the billing period.",
        "I changed my mind and want to cancel the order before it ships.",
        "I need to cancel all future bookings under my account.",
        "I want to unsubscribe from all services and close my account entirely.",
        "I need to cancel the add-on package I subscribed to last week.",
        "I want to stop my monthly donation and cancel the recurring payment.",
        "I need to cancel a repair service I booked for tomorrow.",
        "I want to cancel my cloud storage subscription and download my data first.",
    ],
}
